import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { ThemeProvider } from '@emotion/react';
import Head from 'next/head';
import { theme } from '../styles/customTheme';
import { Container } from '@mui/material';
import { ContactContextProvider } from '../context/ContactContext';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ContactContextProvider>
      <ThemeProvider theme={theme}>
        <Head>
          <title>Backbone Challenge</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container>
          <Component {...pageProps} />
        </Container>
      </ThemeProvider>
    </ContactContextProvider>
  );
}

export default MyApp;
