import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { ThemeProvider } from '@emotion/react';
import Head from 'next/head';
import { theme } from '../styles/customTheme';
import { Container, Fab, IconButton, Tooltip } from '@mui/material';
import { ContactContextProvider } from '../context/ContactContext';
import AddIcon from '@mui/icons-material/Add';
import { useRouter } from 'next/router';
import ArrowBackIosNewRoundedIcon from '@mui/icons-material/ArrowBackIosNewRounded';
import { Provider } from 'react-redux';
import store from '../context/state/store';

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const { pathname } = router;

  return (
    <Provider store={store}>
      <ContactContextProvider>
        <ThemeProvider theme={theme}>
          <Head>
            <title>Backbone Challenge</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Container>
            {pathname !== '/' && pathname !== '/contacts' && (
              <>
                <Tooltip
                  title="Back"
                  sx={{ position: 'absolute', left: '20px', top: '20px' }}
                >
                  <IconButton onClick={() => router.push('/contacts')}>
                    <ArrowBackIosNewRoundedIcon />
                  </IconButton>
                </Tooltip>
              </>
            )}
            {pathname !== '/' && pathname !== '/contacts/create' && (
              <>
                <Tooltip
                  title="Create"
                  sx={{ position: 'absolute', right: '20px', top: '20px' }}
                >
                  <Fab
                    color="primary"
                    size="medium"
                    aria-label="add"
                    onClick={() => router.push('/contacts/create')}
                  >
                    <AddIcon />
                  </Fab>
                </Tooltip>
              </>
            )}
            <Component {...pageProps} />
          </Container>
        </ThemeProvider>
      </ContactContextProvider>
    </Provider>
  );
}

export default MyApp;
