import { Container, ThemeProvider, Typography, Button } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import TurnLeftIcon from '@mui/icons-material/TurnLeft';
import { theme } from '../styles/customTheme';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        sx={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'start',
          minHeight: '90vh',
        }}
      >
        <Typography variant="h2">Backbone Challenge</Typography>

        <Link href="/contacts">
          <Button
            variant="text"
            size="large"
            startIcon={<TurnLeftIcon sx={{ rotate: '180deg' }} />}
          >
            Contact List
          </Button>
        </Link>
      </Container>
    </ThemeProvider>
  );
};

export default Home;
